FHIR_VERSION=R4
fhirServerConfigClass=ca.uhn.fhir.jpa.demo.FhirServerConfigR4
fhirTesterConfigClass=ca.uhn.fhir.jpa.demo.FhirTesterConfigR4
jpaDemoClass=ca.uhn.fhir.jpa.demo.JpaServerDemoR4
jpaDemoMapping=/fhir/*
baseFhirMapping=fhir
